resolver: lts-20.1
packages:
  - .
extra-deps:
  - hashable-1.3.5.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: fc4a89b91fad8b7a02b72901381d4358a470e230
    subdirs:
      - .
      - liquidhaskell-boot
      - liquid-prelude
      - liquid-vector
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: eb339f9abdf073f8d9f0c446c309006fdf49ed42

  - git: https://github.com/ucsd-progsys/lh-plugin-demo
    commit: e7f7a51035f828bae5f2562787c4bcb3720f5529

nix:
  packages: [cacert, git, hostname, z3]
